"""
Diverse vocabulary organized by topic domain for realistic synthetic text generation.

Each topic has: nouns (~100-200), topic-specific verbs (~20), and templates (~10).
Shared vocabulary (connectors, action verbs, adjectives) is used across all topics.

Total: ~3,500+ unique terms across 20 domains.
"""

# =============================================================================
# Shared vocabulary used across all topics
# =============================================================================

CONNECTORS = [
    "the", "a", "an", "this", "that", "with", "for", "from", "in", "on",
    "at", "to", "by", "using", "about", "between", "across", "through",
    "into", "over", "under", "after", "before", "during", "while", "when",
    "where", "how", "what", "why", "and", "or", "but", "so", "because",
    "if", "then", "also", "both", "each", "every", "some", "any", "all",
    "most", "other", "another", "such", "like", "including", "without",
    "within", "against", "along", "around", "behind", "below", "beyond",
    "despite", "except", "inside", "outside", "since", "until", "upon",
]

ACTION_VERBS = [
    "implement", "configure", "optimize", "debug", "fix", "refactor",
    "deploy", "test", "monitor", "migrate", "update", "create", "delete",
    "modify", "build", "run", "install", "setup", "integrate", "connect",
    "parse", "validate", "serialize", "transform", "aggregate", "filter",
    "sort", "cache", "queue", "schedule", "retry", "rollback", "backup",
    "restore", "encrypt", "compress", "authenticate", "authorize",
    "provision", "scale", "analyze", "benchmark", "profile", "trace",
    "inspect", "audit", "export", "import", "generate", "compile",
]

ADJECTIVES = [
    "async", "concurrent", "distributed", "scalable", "persistent",
    "immutable", "stateless", "reactive", "declarative", "idempotent",
    "ephemeral", "deterministic", "redundant", "fault-tolerant",
    "high-availability", "low-latency", "thread-safe", "backward-compatible",
    "cross-platform", "real-time", "incremental", "recursive", "parallel",
    "sequential", "transactional", "atomic", "eventual", "consistent",
    "durable", "volatile", "lazy", "eager", "mutable", "polymorphic",
    "generic", "abstract", "concrete", "nested", "flattened", "normalized",
]

# =============================================================================
# Templates shared across topics (slots: [verb], [noun], [adj], [conn])
# =============================================================================

GENERIC_TEMPLATES = [
    "[verb] the [noun] [conn] [noun] [conn] the [noun]",
    "I need to [verb] [adj] [noun] for [noun] [conn] [noun] handling",
    "How do I [verb] the [noun] [noun] when [noun] [conn] [noun] fails",
    "Can you help [verb] the [noun] [conn] [noun] [conn] the [noun] configuration",
    "The [noun] [noun] is [conn] [noun] [conn] [noun] errors",
    "Please [verb] the [noun] [conn] [noun] so that [noun] [conn] [noun] works",
    "I want to [verb] [adj] [noun] [conn] [noun] [conn] better [noun] performance",
    "What is the best way to [verb] [noun] [conn] [noun] [conn] [noun]",
    "We need to [verb] the [noun] [noun] before [noun] [conn] [noun] deployment",
    "Help me [verb] [adj] [noun] [conn] [noun] [conn] the existing [noun]",
    "[verb] [adj] [noun] [conn] [noun] and then [verb] the [noun] [noun]",
    "After [conn] [noun] [noun] I need to [verb] the [noun] [conn] [noun]",
]

# =============================================================================
# Topic domains
# =============================================================================

TOPICS = {
    "web_frontend": {
        "weight": 0.10,
        "nouns": [
            "component", "hook", "state", "props", "render", "layout", "style",
            "CSS", "DOM", "event", "handler", "listener", "callback", "ref",
            "context", "provider", "consumer", "portal", "fragment", "suspense",
            "boundary", "fallback", "hydration", "SSR", "SSG", "ISR", "virtual-DOM",
            "reconciliation", "fiber", "effect", "memo", "reducer", "dispatch",
            "action", "selector", "slot", "directive", "template", "binding",
            "interpolation", "lifecycle", "mounted", "unmounted", "watcher",
            "computed", "reactive", "signal", "store", "router", "route",
            "navigation", "link", "transition", "animation", "keyframe",
            "transform", "flexbox", "grid", "viewport", "breakpoint", "media-query",
            "responsive", "accessibility", "ARIA", "semantic", "heading", "landmark",
            "focus", "tab-index", "screen-reader", "contrast", "color-scheme",
            "dark-mode", "theme", "design-token", "spacing", "typography",
            "font", "icon", "SVG", "canvas", "WebGL", "intersection-observer",
            "resize-observer", "mutation-observer", "service-worker", "PWA",
            "manifest", "offline", "cache-first", "stale-while-revalidate",
            "code-splitting", "lazy-loading", "tree-shaking", "bundle", "chunk",
            "source-map", "hot-reload", "HMR", "dev-server", "proxy",
            "Tailwind", "styled-components", "CSS-modules", "PostCSS", "Sass",
            "Next.js", "Nuxt", "Remix", "Astro", "Svelte", "SolidJS",
        ],
        "verbs": [
            "render", "hydrate", "mount", "unmount", "dispatch", "emit",
            "bind", "interpolate", "navigate", "transition", "animate",
            "lazy-load", "prefetch", "prerender", "revalidate", "memoize",
            "debounce", "throttle", "virtualize", "paginate",
        ],
    },
    "backend_api": {
        "weight": 0.10,
        "nouns": [
            "endpoint", "route", "handler", "middleware", "controller", "service",
            "repository", "model", "schema", "validation", "serializer",
            "deserializer", "request", "response", "header", "body", "query",
            "parameter", "path", "method", "GET", "POST", "PUT", "DELETE",
            "PATCH", "OPTIONS", "status-code", "error", "exception", "payload",
            "JSON", "XML", "protobuf", "gRPC", "REST", "GraphQL", "WebSocket",
            "SSE", "webhook", "callback-URL", "CORS", "origin", "preflight",
            "authentication", "authorization", "session", "cookie", "token",
            "JWT", "OAuth", "API-key", "rate-limit", "throttle", "quota",
            "pagination", "cursor", "offset", "limit", "sort", "filter",
            "search", "full-text", "fuzzy", "regex", "wildcard",
            "versioning", "deprecation", "migration", "backward-compatibility",
            "idempotency", "retry", "circuit-breaker", "fallback", "timeout",
            "deadline", "keepalive", "connection-pool", "socket", "TLS",
            "certificate", "handshake", "compression", "gzip", "brotli",
            "content-type", "accept", "encoding", "caching", "ETag",
            "If-None-Match", "Cache-Control", "max-age", "no-cache",
            "Express", "FastAPI", "Django", "Flask", "Spring", "Gin", "Fiber",
            "NestJS", "Hono", "Actix", "Axum", "Rocket", "Rails", "Laravel",
        ],
        "verbs": [
            "route", "handle", "serialize", "deserialize", "validate",
            "authenticate", "authorize", "paginate", "throttle", "version",
            "deprecate", "retry", "timeout", "compress", "decompress",
            "negotiate", "proxy", "forward", "redirect", "stream",
        ],
    },
    "database": {
        "weight": 0.08,
        "nouns": [
            "query", "table", "column", "row", "index", "primary-key",
            "foreign-key", "constraint", "unique", "null", "default",
            "migration", "schema", "relation", "join", "inner-join",
            "left-join", "cross-join", "subquery", "CTE", "window-function",
            "partition", "aggregate", "GROUP-BY", "HAVING", "ORDER-BY",
            "WHERE", "SELECT", "INSERT", "UPDATE", "DELETE", "UPSERT",
            "transaction", "commit", "rollback", "savepoint", "isolation",
            "read-committed", "serializable", "deadlock", "lock", "mutex",
            "connection-pool", "prepared-statement", "parameterized-query",
            "SQL-injection", "ORM", "query-builder", "raw-SQL", "stored-procedure",
            "trigger", "view", "materialized-view", "sequence", "auto-increment",
            "UUID", "timestamp", "JSON-column", "array-column", "full-text-search",
            "tsvector", "trigram", "B-tree", "hash-index", "GIN", "GiST",
            "BRIN", "partial-index", "covering-index", "expression-index",
            "EXPLAIN", "ANALYZE", "query-plan", "sequential-scan", "index-scan",
            "bitmap-scan", "nested-loop", "hash-join", "merge-join",
            "vacuum", "autovacuum", "reindex", "bloat", "dead-tuples",
            "WAL", "replication", "streaming-replication", "logical-replication",
            "failover", "hot-standby", "read-replica", "sharding", "partitioning",
            "PostgreSQL", "MySQL", "SQLite", "MongoDB", "Redis", "Cassandra",
            "DynamoDB", "CockroachDB", "TimescaleDB", "ClickHouse", "Elasticsearch",
        ],
        "verbs": [
            "query", "index", "migrate", "join", "aggregate", "partition",
            "shard", "replicate", "vacuum", "reindex", "normalize",
            "denormalize", "seed", "truncate", "upsert", "bulk-insert",
            "paginate", "materialize", "invalidate", "failover",
        ],
    },
    "devops": {
        "weight": 0.08,
        "nouns": [
            "container", "image", "Dockerfile", "layer", "registry", "tag",
            "digest", "volume", "mount", "network", "bridge", "overlay",
            "pod", "deployment", "service", "ingress", "namespace", "node",
            "cluster", "kubelet", "kube-proxy", "etcd", "control-plane",
            "scheduler", "controller", "operator", "CRD", "helm-chart",
            "values", "template", "release", "rollout", "canary", "blue-green",
            "rolling-update", "replica-set", "daemon-set", "stateful-set",
            "job", "cron-job", "config-map", "secret", "PVC", "storage-class",
            "resource-limit", "request", "HPA", "VPA", "affinity", "taint",
            "toleration", "label", "annotation", "selector",
            "pipeline", "stage", "step", "artifact", "trigger", "webhook",
            "runner", "agent", "executor", "cache", "matrix", "parallel",
            "GitHub-Actions", "GitLab-CI", "Jenkins", "CircleCI", "ArgoCD",
            "Terraform", "Ansible", "Pulumi", "CloudFormation",
            "IaC", "state-file", "plan", "apply", "drift", "import",
            "module", "provider", "resource", "data-source", "output",
            "variable", "backend", "workspace", "environment",
        ],
        "verbs": [
            "containerize", "orchestrate", "provision", "deploy", "rollout",
            "rollback", "scale", "drain", "cordon", "taint", "label",
            "annotate", "helm-install", "helm-upgrade", "terraform-apply",
            "terraform-plan", "ansible-playbook", "pipeline-trigger",
            "canary-release", "blue-green-deploy",
        ],
    },
    "cloud": {
        "weight": 0.07,
        "nouns": [
            "S3", "bucket", "object", "prefix", "lifecycle", "versioning",
            "Lambda", "function", "invocation", "cold-start", "warm-pool",
            "layer", "runtime", "handler", "event-source", "trigger",
            "EC2", "instance", "AMI", "snapshot", "EBS", "volume",
            "security-group", "key-pair", "user-data", "metadata",
            "VPC", "subnet", "route-table", "internet-gateway", "NAT-gateway",
            "CIDR", "peering", "transit-gateway", "endpoint",
            "IAM", "role", "policy", "permission", "principal", "trust",
            "STS", "assume-role", "cross-account", "federation",
            "CloudFormation", "stack", "template", "parameter", "output",
            "nested-stack", "change-set", "drift-detection",
            "ECS", "Fargate", "task-definition", "service", "cluster",
            "ALB", "NLB", "target-group", "health-check", "listener",
            "CloudWatch", "metric", "alarm", "log-group", "log-stream",
            "SNS", "SQS", "EventBridge", "Step-Functions", "state-machine",
            "RDS", "Aurora", "ElastiCache", "DynamoDB", "Kinesis",
            "API-Gateway", "CloudFront", "Route53", "ACM", "WAF",
            "GCP", "Azure", "DigitalOcean", "Linode", "Hetzner",
        ],
        "verbs": [
            "provision", "launch", "terminate", "attach", "detach",
            "associate", "disassociate", "peer", "assume", "federate",
            "invoke", "trigger", "subscribe", "publish", "stream",
            "replicate", "failover", "snapshot", "restore", "migrate",
        ],
    },
    "python": {
        "weight": 0.08,
        "nouns": [
            "decorator", "generator", "iterator", "comprehension", "lambda",
            "closure", "context-manager", "descriptor", "metaclass", "mixin",
            "abstract-class", "dataclass", "protocol", "type-hint", "annotation",
            "TypeVar", "Generic", "Optional", "Union", "Literal", "TypedDict",
            "Pydantic", "BaseModel", "validator", "field", "serialization",
            "virtual-environment", "venv", "pip", "poetry", "conda",
            "requirements", "lockfile", "wheel", "sdist", "package",
            "module", "namespace", "import", "__init__", "__main__",
            "asyncio", "coroutine", "event-loop", "future", "task",
            "gather", "semaphore", "aiohttp", "httpx", "FastAPI",
            "Django", "Flask", "SQLAlchemy", "Alembic", "Celery",
            "pytest", "fixture", "conftest", "parametrize", "mock",
            "patch", "monkeypatch", "coverage", "tox", "nox",
            "pandas", "DataFrame", "Series", "groupby", "merge",
            "pivot", "melt", "apply", "vectorize", "rolling",
            "numpy", "ndarray", "broadcasting", "slicing", "indexing",
            "matplotlib", "seaborn", "plotly", "bokeh", "altair",
            "logging", "handler", "formatter", "filter", "level",
            "pathlib", "Path", "glob", "shutil", "tempfile",
            "subprocess", "Popen", "PIPE", "returncode", "timeout",
            "argparse", "click", "typer", "rich", "tqdm",
        ],
        "verbs": [
            "decorate", "yield", "iterate", "comprehend", "annotate",
            "serialize", "deserialize", "validate", "patch", "mock",
            "parametrize", "vectorize", "broadcast", "slice", "index",
            "groupby", "merge", "pivot", "apply", "gather",
        ],
    },
    "javascript": {
        "weight": 0.08,
        "nouns": [
            "promise", "async-await", "callback", "closure", "prototype",
            "class", "module", "import", "export", "default-export",
            "named-export", "barrel-file", "tree-shaking", "dead-code",
            "CommonJS", "ESM", "AMD", "UMD", "IIFE",
            "event-loop", "microtask", "macrotask", "setTimeout",
            "setInterval", "requestAnimationFrame", "AbortController",
            "fetch", "XMLHttpRequest", "FormData", "Blob", "ArrayBuffer",
            "TypedArray", "SharedArrayBuffer", "Atomics", "Worker",
            "ServiceWorker", "WebSocket", "EventSource", "BroadcastChannel",
            "npm", "yarn", "pnpm", "bun", "deno", "node",
            "package.json", "lockfile", "workspace", "monorepo",
            "webpack", "vite", "esbuild", "rollup", "parcel", "turbopack",
            "babel", "swc", "TypeScript", "tsconfig", "declaration",
            "interface", "type-alias", "enum", "tuple", "union",
            "intersection", "generic", "conditional-type", "mapped-type",
            "utility-type", "Partial", "Required", "Pick", "Omit",
            "ESLint", "Prettier", "Biome", "husky", "lint-staged",
            "jest", "vitest", "mocha", "chai", "cypress", "playwright",
            "Storybook", "testing-library", "snapshot-test", "e2e-test",
            "Express", "Fastify", "Koa", "Hono", "NestJS", "tRPC",
            "Prisma", "Drizzle", "Knex", "Sequelize", "TypeORM",
        ],
        "verbs": [
            "await", "resolve", "reject", "chain", "destructure",
            "spread", "rest", "transpile", "bundle", "minify",
            "polyfill", "lint", "format", "typecheck", "scaffold",
            "bootstrap", "eject", "prebuild", "postinstall", "publish",
        ],
    },
    "data_science": {
        "weight": 0.06,
        "nouns": [
            "model", "training", "inference", "dataset", "feature",
            "label", "target", "prediction", "classification", "regression",
            "clustering", "dimensionality-reduction", "embedding", "vector",
            "transformer", "attention", "self-attention", "cross-attention",
            "encoder", "decoder", "tokenizer", "vocabulary", "subword",
            "BPE", "SentencePiece", "fine-tuning", "transfer-learning",
            "pre-training", "RLHF", "DPO", "LoRA", "QLoRA", "adapter",
            "quantization", "INT8", "FP16", "BF16", "mixed-precision",
            "gradient", "backpropagation", "optimizer", "learning-rate",
            "scheduler", "warmup", "cosine-annealing", "weight-decay",
            "batch-size", "epoch", "iteration", "step", "checkpoint",
            "loss-function", "cross-entropy", "MSE", "MAE", "focal-loss",
            "accuracy", "precision", "recall", "F1-score", "AUC-ROC",
            "confusion-matrix", "perplexity", "BLEU", "ROUGE", "BERTScore",
            "overfitting", "underfitting", "regularization", "dropout",
            "batch-normalization", "layer-normalization", "residual",
            "skip-connection", "activation", "ReLU", "GELU", "SiLU",
            "softmax", "sigmoid", "tanh", "linear", "convolution",
            "pooling", "recurrent", "LSTM", "GRU", "bidirectional",
            "PyTorch", "TensorFlow", "JAX", "Hugging-Face", "scikit-learn",
            "XGBoost", "LightGBM", "CatBoost", "ONNX", "TensorRT",
        ],
        "verbs": [
            "train", "fine-tune", "evaluate", "predict", "classify",
            "cluster", "embed", "tokenize", "quantize", "prune",
            "distill", "augment", "normalize", "standardize", "impute",
            "encode", "decode", "sample", "generate", "infer",
        ],
    },
    "testing": {
        "weight": 0.05,
        "nouns": [
            "unit-test", "integration-test", "end-to-end-test", "smoke-test",
            "regression-test", "acceptance-test", "load-test", "stress-test",
            "property-test", "fuzz-test", "snapshot-test", "visual-test",
            "assertion", "expectation", "matcher", "mock", "stub", "spy",
            "fake", "double", "fixture", "factory", "builder", "seed",
            "setup", "teardown", "before-each", "after-each", "before-all",
            "describe", "it", "test", "spec", "suite", "runner",
            "reporter", "coverage", "branch-coverage", "line-coverage",
            "statement-coverage", "function-coverage", "threshold",
            "CI", "CD", "pipeline", "gate", "quality-gate", "SonarQube",
            "pytest", "jest", "vitest", "mocha", "JUnit", "TestNG",
            "Cypress", "Playwright", "Selenium", "WebDriver", "Puppeteer",
            "locator", "selector", "page-object", "step-definition",
            "given", "when", "then", "scenario", "feature-file",
            "test-plan", "test-case", "test-data", "golden-file",
            "flaky-test", "retry", "timeout", "parallel-execution",
            "test-isolation", "deterministic", "idempotent", "hermetic",
        ],
        "verbs": [
            "assert", "expect", "mock", "stub", "spy", "fake",
            "isolate", "parameterize", "fuzz", "snapshot", "instrument",
            "measure", "cover", "gate", "retry", "parallelize",
            "seed", "fixture", "teardown", "verify",
        ],
    },
    "security": {
        "weight": 0.05,
        "nouns": [
            "encryption", "decryption", "cipher", "AES", "RSA", "ECDSA",
            "Ed25519", "hash", "SHA-256", "HMAC", "salt", "pepper",
            "nonce", "IV", "key-derivation", "PBKDF2", "bcrypt", "scrypt",
            "argon2", "certificate", "CA", "chain-of-trust", "X.509",
            "TLS", "mTLS", "handshake", "cipher-suite", "ALPN",
            "OAuth", "OpenID-Connect", "SAML", "LDAP", "SSO",
            "JWT", "access-token", "refresh-token", "scope", "claim",
            "RBAC", "ABAC", "ACL", "permission", "role", "principal",
            "vulnerability", "CVE", "OWASP", "XSS", "CSRF", "SSRF",
            "SQL-injection", "command-injection", "path-traversal",
            "deserialization", "prototype-pollution", "timing-attack",
            "side-channel", "brute-force", "credential-stuffing",
            "rate-limiting", "CAPTCHA", "WAF", "SAST", "DAST", "SCA",
            "secrets-manager", "vault", "KMS", "HSM", "key-rotation",
            "audit-log", "compliance", "SOC2", "GDPR", "HIPAA", "PCI-DSS",
            "penetration-test", "red-team", "blue-team", "incident-response",
            "zero-trust", "least-privilege", "defense-in-depth",
        ],
        "verbs": [
            "encrypt", "decrypt", "sign", "verify", "hash",
            "authenticate", "authorize", "rotate", "revoke", "audit",
            "scan", "patch", "harden", "isolate", "quarantine",
            "escalate", "remediate", "mitigate", "detect", "respond",
        ],
    },
    "networking": {
        "weight": 0.04,
        "nouns": [
            "TCP", "UDP", "HTTP", "HTTPS", "HTTP/2", "HTTP/3", "QUIC",
            "DNS", "A-record", "CNAME", "MX", "TXT", "NS", "SOA",
            "TTL", "resolver", "recursive", "authoritative", "zone",
            "IP", "IPv4", "IPv6", "CIDR", "subnet", "gateway",
            "router", "switch", "firewall", "ACL", "iptables", "nftables",
            "load-balancer", "reverse-proxy", "forward-proxy", "CDN",
            "edge", "origin", "POP", "anycast", "unicast", "multicast",
            "socket", "port", "bind", "listen", "accept", "connect",
            "send", "receive", "close", "half-close", "keepalive",
            "RTT", "latency", "bandwidth", "throughput", "jitter",
            "packet-loss", "congestion", "window-size", "backpressure",
            "Nginx", "HAProxy", "Envoy", "Traefik", "Caddy",
            "WireGuard", "OpenVPN", "IPSec", "VPN", "tunnel",
            "mDNS", "DHCP", "ARP", "NDP", "ICMP", "traceroute",
        ],
        "verbs": [
            "route", "forward", "proxy", "balance", "resolve",
            "bind", "listen", "connect", "handshake", "negotiate",
            "tunnel", "encapsulate", "fragment", "reassemble", "multiplex",
            "demultiplex", "throttle", "shape", "filter", "inspect",
        ],
    },
    "git_vcs": {
        "weight": 0.05,
        "nouns": [
            "repository", "branch", "commit", "merge", "rebase", "cherry-pick",
            "stash", "tag", "release", "diff", "patch", "conflict",
            "resolution", "fast-forward", "three-way-merge", "octopus-merge",
            "squash", "fixup", "amend", "interactive-rebase", "reflog",
            "HEAD", "detached-HEAD", "remote", "origin", "upstream",
            "fetch", "pull", "push", "force-push", "force-with-lease",
            "clone", "fork", "mirror", "shallow-clone", "sparse-checkout",
            "submodule", "subtree", "worktree", "bare-repository",
            "hook", "pre-commit", "pre-push", "post-merge", "commit-msg",
            "gitignore", "gitattributes", "git-lfs", "large-file",
            "pull-request", "merge-request", "review", "approval",
            "CI-check", "status-check", "branch-protection", "CODEOWNERS",
            "monorepo", "polyrepo", "trunk-based", "git-flow", "GitHub-flow",
            "conventional-commits", "semantic-versioning", "changelog",
        ],
        "verbs": [
            "commit", "merge", "rebase", "cherry-pick", "stash",
            "tag", "branch", "checkout", "switch", "fetch",
            "pull", "push", "clone", "fork", "squash",
            "amend", "bisect", "blame", "log", "diff",
        ],
    },
    "linux_shell": {
        "weight": 0.05,
        "nouns": [
            "bash", "zsh", "fish", "shell", "terminal", "TTY", "PTY",
            "process", "PID", "thread", "signal", "SIGTERM", "SIGKILL",
            "SIGHUP", "daemon", "foreground", "background", "job-control",
            "pipe", "redirect", "stdin", "stdout", "stderr", "file-descriptor",
            "grep", "awk", "sed", "cut", "sort", "uniq", "wc", "head",
            "tail", "tee", "xargs", "find", "locate", "which", "whereis",
            "chmod", "chown", "chgrp", "umask", "permission", "sticky-bit",
            "SUID", "SGID", "ACL", "SELinux", "AppArmor",
            "systemd", "service", "unit-file", "timer", "socket", "target",
            "journalctl", "syslog", "rsyslog", "logrotate",
            "cron", "crontab", "at", "anacron", "systemd-timer",
            "package-manager", "apt", "yum", "dnf", "pacman", "brew",
            "snap", "flatpak", "AppImage", "dpkg", "rpm",
            "filesystem", "ext4", "XFS", "btrfs", "ZFS", "FUSE",
            "mount", "fstab", "inode", "block", "superblock",
            "LVM", "LUKS", "partition", "fdisk", "parted", "df", "du",
            "top", "htop", "ps", "kill", "nice", "renice", "nohup",
            "screen", "tmux", "strace", "ltrace", "lsof", "netstat",
        ],
        "verbs": [
            "grep", "pipe", "redirect", "chmod", "mount", "unmount",
            "kill", "signal", "schedule", "rotate", "archive",
            "compress", "extract", "symlink", "trace", "profile",
            "partition", "format", "benchmark", "monitor",
        ],
    },
    "monitoring": {
        "weight": 0.04,
        "nouns": [
            "metric", "counter", "gauge", "histogram", "summary",
            "label", "dimension", "cardinality", "time-series",
            "scrape", "push", "pull", "exporter", "collector",
            "Prometheus", "Grafana", "Datadog", "New-Relic", "Splunk",
            "OpenTelemetry", "OTLP", "Jaeger", "Zipkin", "Tempo",
            "trace", "span", "context", "propagation", "baggage",
            "log", "structured-log", "log-level", "correlation-ID",
            "ELK", "Elasticsearch", "Logstash", "Kibana", "Fluentd",
            "Loki", "Promtail", "Vector", "Fluent-Bit",
            "dashboard", "panel", "visualization", "query", "PromQL",
            "LogQL", "alert", "alerting-rule", "recording-rule",
            "notification", "channel", "escalation", "on-call",
            "PagerDuty", "OpsGenie", "Slack-webhook", "email-alert",
            "SLO", "SLI", "SLA", "error-budget", "burn-rate",
            "availability", "uptime", "MTTD", "MTTR", "MTTF",
            "incident", "postmortem", "root-cause", "runbook",
        ],
        "verbs": [
            "scrape", "collect", "aggregate", "alert", "notify",
            "escalate", "correlate", "visualize", "query", "export",
            "instrument", "trace", "sample", "propagate", "annotate",
            "acknowledge", "silence", "resolve", "page", "triage",
        ],
    },
    "performance": {
        "weight": 0.04,
        "nouns": [
            "profiler", "flame-graph", "call-graph", "hot-path", "bottleneck",
            "benchmark", "throughput", "latency", "P50", "P95", "P99",
            "percentile", "histogram", "distribution", "outlier",
            "cache", "L1", "L2", "L3", "TLB", "page-fault", "cache-miss",
            "cache-hit", "prefetch", "eviction", "LRU", "LFU", "TTL",
            "memory-leak", "heap", "stack", "allocation", "GC",
            "garbage-collection", "mark-sweep", "generational", "compaction",
            "reference-counting", "weak-reference", "finalization",
            "CPU", "core", "thread", "context-switch", "syscall",
            "user-space", "kernel-space", "interrupt", "DMA",
            "SIMD", "vectorization", "AVX", "SSE", "NEON",
            "branch-prediction", "speculative-execution", "pipeline-stall",
            "IPC", "CPI", "throughput", "bandwidth", "IOPS",
            "sequential-read", "random-read", "write-amplification",
            "compaction", "bloom-filter", "skip-list", "B-tree",
            "LSM-tree", "WAL", "fsync", "direct-IO", "mmap",
            "connection-pool", "thread-pool", "event-loop", "epoll",
            "io_uring", "kqueue", "IOCP", "non-blocking",
        ],
        "verbs": [
            "profile", "benchmark", "optimize", "cache", "prefetch",
            "evict", "allocate", "free", "compact", "defragment",
            "parallelize", "vectorize", "inline", "unroll", "specialize",
            "pool", "batch", "coalesce", "amortize", "pipeline",
        ],
    },
    "documentation": {
        "weight": 0.03,
        "nouns": [
            "README", "CHANGELOG", "CONTRIBUTING", "LICENSE", "CODE-OF-CONDUCT",
            "API-documentation", "reference", "guide", "tutorial", "how-to",
            "concept", "explanation", "ADR", "RFC", "proposal",
            "architecture", "diagram", "flowchart", "sequence-diagram",
            "class-diagram", "entity-relationship", "state-machine",
            "Mermaid", "PlantUML", "draw.io", "Excalidraw",
            "Markdown", "reStructuredText", "AsciiDoc", "LaTeX",
            "Sphinx", "MkDocs", "Docusaurus", "VitePress", "Mintlify",
            "Swagger", "OpenAPI", "Redoc", "Stoplight", "Postman",
            "JSDoc", "TypeDoc", "pydoc", "Javadoc", "rustdoc", "godoc",
            "code-comment", "docstring", "annotation", "tag",
            "versioning", "deprecation-notice", "migration-guide",
            "release-notes", "breaking-change", "feature-flag",
        ],
        "verbs": [
            "document", "annotate", "describe", "explain", "diagram",
            "reference", "cross-reference", "version", "deprecate",
            "publish", "generate", "render", "preview", "review",
            "proofread", "update", "maintain", "archive", "translate", "link",
        ],
    },
    "build_systems": {
        "weight": 0.03,
        "nouns": [
            "Makefile", "target", "dependency", "recipe", "variable",
            "phony", "prerequisite", "pattern-rule", "implicit-rule",
            "CMake", "CMakeLists", "generator", "build-type", "toolchain",
            "Cargo", "crate", "workspace", "feature-flag", "edition",
            "Go-modules", "go.mod", "go.sum", "vendor", "proxy",
            "Gradle", "build.gradle", "task", "plugin", "repository",
            "Maven", "pom.xml", "artifact", "dependency-management",
            "Bazel", "BUILD", "WORKSPACE", "rule", "target", "action",
            "compilation", "linking", "static-library", "shared-library",
            "object-file", "executable", "debug-symbols", "strip",
            "cross-compilation", "sysroot", "toolchain-file",
            "incremental-build", "build-cache", "remote-cache",
            "reproducible-build", "deterministic", "hermetic",
            "CI-build", "release-build", "debug-build", "sanitizer",
            "AddressSanitizer", "ThreadSanitizer", "UndefinedBehavior",
        ],
        "verbs": [
            "compile", "link", "build", "clean", "rebuild",
            "install", "package", "publish", "release", "cross-compile",
            "strip", "optimize", "instrument", "sanitize", "lint",
            "format", "check", "verify", "sign", "notarize",
        ],
    },
    "storage": {
        "weight": 0.03,
        "nouns": [
            "block-storage", "object-storage", "file-storage", "NFS",
            "CIFS", "SMB", "iSCSI", "Fibre-Channel", "NVMe", "NVMe-oF",
            "SSD", "HDD", "NVMe-SSD", "RAID", "RAID-0", "RAID-1",
            "RAID-5", "RAID-6", "RAID-10", "erasure-coding",
            "replication", "mirroring", "striping", "parity",
            "snapshot", "clone", "thin-provisioning", "thick-provisioning",
            "deduplication", "compression", "encryption-at-rest",
            "tiering", "hot-tier", "warm-tier", "cold-tier", "archive",
            "lifecycle-policy", "retention", "expiration",
            "throughput", "IOPS", "latency", "bandwidth", "queue-depth",
            "write-amplification", "wear-leveling", "garbage-collection",
            "TRIM", "discard", "over-provisioning",
            "Ceph", "MinIO", "GlusterFS", "Longhorn", "Rook",
            "WEKA", "Lustre", "GPFS", "BeeGFS", "NetApp",
            "EBS", "EFS", "FSx", "S3-Glacier", "Azure-Blob",
        ],
        "verbs": [
            "store", "retrieve", "replicate", "snapshot", "clone",
            "deduplicate", "compress", "encrypt", "tier", "archive",
            "provision", "expand", "shrink", "migrate", "evacuate",
            "stripe", "mirror", "scrub", "heal", "rebalance",
        ],
    },
    "message_queues": {
        "weight": 0.03,
        "nouns": [
            "Kafka", "topic", "partition", "offset", "consumer-group",
            "producer", "consumer", "broker", "ZooKeeper", "KRaft",
            "replication-factor", "ISR", "leader", "follower",
            "RabbitMQ", "exchange", "queue", "binding", "routing-key",
            "fanout", "direct", "topic-exchange", "headers-exchange",
            "dead-letter-queue", "TTL", "priority-queue", "acknowledgment",
            "Redis", "pub/sub", "stream", "consumer-group", "XREAD",
            "XADD", "XACK", "XPENDING", "XCLAIM",
            "NATS", "JetStream", "subject", "subscription", "durable",
            "Pulsar", "namespace", "tenant", "bookkeeper", "ledger",
            "SQS", "SNS", "EventBridge", "Kinesis", "Firehose",
            "event-driven", "event-sourcing", "CQRS", "saga",
            "choreography", "orchestration", "compensation",
            "exactly-once", "at-least-once", "at-most-once",
            "idempotent", "deduplication", "ordering", "FIFO",
            "backpressure", "flow-control", "rate-limiting",
            "schema-registry", "Avro", "Protobuf", "JSON-Schema",
        ],
        "verbs": [
            "produce", "consume", "publish", "subscribe", "acknowledge",
            "commit", "seek", "replay", "compact", "retain",
            "route", "fanout", "dead-letter", "retry", "compensate",
            "orchestrate", "choreograph", "serialize", "deserialize", "validate",
        ],
    },
    "mobile": {
        "weight": 0.03,
        "nouns": [
            "iOS", "Android", "React-Native", "Flutter", "Swift",
            "Kotlin", "Objective-C", "Java", "Dart", "SwiftUI",
            "Jetpack-Compose", "UIKit", "View", "ViewController",
            "Activity", "Fragment", "Intent", "Bundle", "ViewModel",
            "LiveData", "StateFlow", "Combine", "publisher", "subscriber",
            "navigation", "deep-link", "universal-link", "scheme",
            "notification", "push-notification", "APNs", "FCM",
            "background-task", "foreground-service", "work-manager",
            "Core-Data", "Room", "SQLite", "Realm", "UserDefaults",
            "SharedPreferences", "Keychain", "KeyStore",
            "App-Store", "Play-Store", "TestFlight", "Firebase",
            "Crashlytics", "Analytics", "Remote-Config", "A/B-test",
            "Xcode", "Android-Studio", "Gradle", "CocoaPods", "SPM",
            "Fastlane", "Bitrise", "App-Center", "CodePush",
            "accessibility", "VoiceOver", "TalkBack", "dynamic-type",
            "dark-mode", "localization", "internationalization", "RTL",
            "gesture", "haptic", "biometric", "Face-ID", "Touch-ID",
        ],
        "verbs": [
            "navigate", "present", "dismiss", "push", "pop",
            "observe", "bind", "subscribe", "notify", "deep-link",
            "sign", "provision", "archive", "distribute", "localize",
            "animate", "gesture", "haptic", "authenticate", "persist",
        ],
    },
}


def get_all_nouns():
    """Return all unique nouns across all topics."""
    nouns = set()
    for topic in TOPICS.values():
        nouns.update(topic["nouns"])
    return sorted(nouns)


def get_all_verbs():
    """Return all unique verbs (shared + topic-specific)."""
    verbs = set(ACTION_VERBS)
    for topic in TOPICS.values():
        verbs.update(topic["verbs"])
    return sorted(verbs)


def get_topic_names():
    """Return list of topic names with their weights."""
    return [(name, topic["weight"]) for name, topic in TOPICS.items()]


def get_vocabulary_stats():
    """Return stats about the vocabulary."""
    all_nouns = get_all_nouns()
    all_verbs = get_all_verbs()
    return {
        "topics": len(TOPICS),
        "unique_nouns": len(all_nouns),
        "unique_verbs": len(all_verbs),
        "shared_connectors": len(CONNECTORS),
        "shared_adjectives": len(ADJECTIVES),
        "templates": len(GENERIC_TEMPLATES),
        "total_unique_terms": len(all_nouns) + len(all_verbs) + len(CONNECTORS) + len(ADJECTIVES),
    }
